# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [3]:
my_array = np.array([10,20,30,40])
my_2d_array = np.array([[10,20,30,40],[50,60,70,80]])
my_3d_array = np.array([[[10,20,30,40], [50,60,70,80]], [[10,20,30,40], [90,100,110,120]]])
print(my_array)
print(my_2d_array)
print(my_3d_array)

[10 20 30 40]
[[10 20 30 40]
 [50 60 70 80]]
[[[ 10  20  30  40]
  [ 50  60  70  80]]

 [[ 10  20  30  40]
  [ 90 100 110 120]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [5]:
my_array = np.array([10,20,30,40,50])
# 1
print(my_array.ndim)
# (5,)
print(my_array.shape)
# 5
print(my_array.size)
# int64
print(my_array.dtype)
# 8
print(my_array.itemsize)
# <memory at 0x1095a4c48>
print(my_array.data)
# 40
print(my_array.nbytes)

1
(5,)
5
int64
8
40


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [6]:
# ones are filled
ones = np.ones((5,10))
print(ones)
# zeros are filled
zeros = np.zeros((5,10))
print(zeros)
# zeros are filled
empty = np.empty((5,10))
print(empty)
# tens are filled
full = np.full((5,10), 10)
print(full)
# 5 numbers by 5 from 0 - 20
arange = np.arange(0, 20, 5)
print(arange)
# 5 numbers by 5 from 0 - 20
linspace = np.linspace(0,20,num=5)
print(linspace)
# random assortment of numbers with 5 rows and 10 columns
random = np.random.random((5,10))
print(random)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]]
[ 0  5 10 15]
[ 0.  5. 10. 15. 20.]
[[0.48025323 0.45881563 0.54812317 0.1980102  0.28629162 0.95686851
  0.6385498  0.59936603 0.89493606 0.57949473]
 [0.34037513 0.08618562 0.27291363 0.64833898 0.79904701 0.39444345
  0.33439001 0.08346038 0.15174972 0.22845531]
 [0.33797654 0.53041441 0.69816298 0.11185607 0.53811624 0.08226616
  

## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [7]:
a = np.ones((5,10))
b = np.arange(10)
print(f"a: {a}")
print(f"b: {b}")
print(a)
print(b)
print(a + b)
print(a * b)
print(a - b)

a: [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
b: [0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[ 1.  0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [ 1.  0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [ 1.  0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [ 1.  0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [ 1.  0. -1. -2. -3. -4. -5. -6. -7. -8.]]


## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [8]:
a = np.array([10,20,30,40])
b = np.array([50,60,70,80])
c = np.array([90,100,110,120])
# sum of numbers in a
s = np.sum(a)
print(s)
# minimum of array of a and b
minimum = np.minimum(a,b)
print(minimum)
# maximum of array of a and b
maximum = np.maximum(a,b)
print(maximum)
# goes up by n + 10
cu = np.cumsum(a)
print(cu)
# mean of numbers in a
me = np.mean(a)
print(me)
# cofficient of a
corr = np.corrcoef(a)
print(corr)
# standard deviation of a
std = np.std(a)
print(std)
# variance of a
var = np.var(a)
print(var)

100
[10 20 30 40]
[50 60 70 80]
[ 10  30  60 100]
25.0
1.0
11.180339887498949
125.0


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [9]:
a = [True, True, False, False]
b = [False, False, True, True]
# all False
c = np.logical_and(a,b)
print(c)
# all True
d = np.logical_or(a,b)
print(d)
# half False and half True
e = np.logical_not(a)
print(e)

[False False False False]
[ True  True  True  True]
[False False  True  True]
